name: Check
on: push
jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: snok/install-poetry@v1
      - run: poetry install
      - run: poetry run ./check.sh
